Add ports and database name for mariadb
chaoss/grimoirelab-sirmordred pull request #501
Opened 2021-03-31 21:31 UTC by SourabhSaraswat-191939

Signed-off-by: Sourabh Saraswat <saraswatsourabh5@gmail.com>

expose =>as it activates container to listen for a specific port only from the world inside of docker AND not accessible from world outside of the docker . So that's why this create an issue with connection to database when we run micro-mordred .
as per reference [https://docs.docker.com/engine/reference/builder/#expose](https://docs.docker.com/engine/reference/builder/#expose)

So to overcome this we can use :
ports =>  as it activates the container to listen for specified port(s) from the world outside of the docker AND also accessible world inside docker.

and there is one more issue while setting up grimoire lab from docker-compose (with SearchGuard) that it have no database with name of "test_sh" which creates an error "no database of name 'test_sh' " while running micro-mordred .
So for this , i added a database of this name in mysql by default .

2021-04-01 07:40 UTC, vchrombie commented
Related to https://github.com/chaoss/grimoirelab-sirmordred/issues/500#issuecomment-811403908

2021-04-01 07:43 UTC, vchrombie requested changes
Good catch, thank you @SourabhSaraswat-191939.

I understand that the MariaDB can have the same configuration for both docker-compose (with and without search guard). So, it would be great if you can update the search guard mariadb similar to the without search guard.

2021-04-01 07:45 UTC, vchrombie commented
You need not create a new PR, you can add the changes to the same commit.
Please use `--amend` during git commit and `--force` during git push.

Let us know if you need help.

2021-04-01 11:04 UTC, SourabhSaraswat-191939 commented
> it would be great if you can update the search guard mariadb similar to the without search guard.

Sure, i will do that .

> Please use `--amend` during git commit and `--force` during git push.

Okay 👍🏻  .

2021-04-01 11:41 UTC, SourabhSaraswat-191939 commented
If there is any change still requires then let me know that .

2021-04-01 11:49 UTC, vchrombie approved these changes
LGTM, thanks for your contribution.

2021-04-01 11:59 UTC, vchrombie commented
The changes look good to me, but it would be great if you can update the commit message with a small description and a proper title as per the [commit message guidelines](https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#guidelines-to-follow-to-write-good-commit-messages).

```
[docs] Update the mariadb docker-compose configuration

This commit updates the mariadb docker-compose configuration in the 
docker-compose with search guard section of the Getting-Started.md doc.

Resolves: https://github.com/chaoss/grimoirelab-sirmordred/issues/500
```

You can amend the commit, change the commit message and force push it.

Let me know if you need any help.

2021-04-01 12:05 UTC, SourabhSaraswat-191939 commented
> The changes look good to me, but it would be great if you can update the commit message with a small description and a proper title as per the [commit message guidelines](https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#guidelines-to-follow-to-write-good-commit-messages).

Done 👍🏻

2021-04-12 16:43 UTC, sduenas approved these changes
LGTM

2021-04-12 16:44 UTC, merged