Add port custom
chaoss/grimoirelab-sirmordred pull request #545
Opened 2022-04-26 20:51 UTC by jakspok

2022-04-28 05:17 UTC, vchrombie requested changes
Hi @jakspok, thanks for opening the PR.

Can you remove the `.idea` and other not relevant changes from the PR to proceed with the review.

You can just remove them and amend it to the same commit. Also, it would be great if you can squash the commits into one.

2022-04-28 05:17 UTC, vchrombie commented on .idea/.gitignore
> +# Default ignored files
The `.idea` folder has to be removed

2022-04-28 05:17 UTC, vchrombie commented on setup.py
> +      url="https://github.com/jakspok/grimoirelab-sirmordred",
This change has to be reverted

2023-10-13 10:57 UTC, jjmerchante commented
The current version of grimoirelab uses SortingHat service instead of a database. This change is obsolete. Closing the PR

2023-10-13 10:57 UTC, closed without merging