[enrich] Include SortingHat parameters
chaoss/grimoirelab-sirmordred pull request #581
Opened 2023-01-11 13:14 UTC by jjmerchante

This PR includes `sh_port`, `sh_path`, `sh_ssl` parameters to `SortingHat`. These parameters are now mandatory in the configuration.

Configuration files are updated accordingly.

2023-01-12 17:24 UTC, sduenas approved these changes
LGTM

2023-01-12 17:25 UTC, sduenas requested changes
Apparently there's an error on the tests? Any idea why?

2023-01-13 08:01 UTC, jjmerchante commented
This PR depends on: https://github.com/chaoss/grimoirelab-elk/pull/1095

I forgot to mention it in the description

2023-01-16 15:03 UTC, sduenas approved these changes

2023-01-16 15:04 UTC, closed without merging